/*
** EPITECH PROJECT, 2020
** NWP_myteams_2019
** File description:
** length.h
*/

#ifndef NWP_MYTEAMS_2019_SERVER_SRC_DEF_LENGTH_H
#define NWP_MYTEAMS_2019_SERVER_SRC_DEF_LENGTH_H

#define MAX_NAME_LENGTH (32)
#define MAX_DESCRIPTION_LENGTH (255)
#define MAX_BODY_LENGTH (512)
#define UUID_LENGTH (128)

#endif // NWP_MYTEAMS_2019_SERVER_SRC_DEF_LENGTH_H
