/*
** EPITECH PROJECT, 2020
** server
** File description:
** response.h
*/

#ifndef SERVER_SRC_DEF_RESPONSE_H
#define SERVER_SRC_DEF_RESPONSE_H

typedef const char* const c_string;

#define g_string static c_string

g_string RESPONSE_GLOBAL_COMMAND_KO = "GLOBAL COMMAND KO \"%s\"\n";
g_string RESPONSE_GLOBAL_CREATE_KO = "GLOBAL CREATE KO \"%s\"\n";
g_string RESPONSE_GLOBAL_HELP_OK = "GLOBAL HELP OK \"%s\"\n";
g_string RESPONSE_GLOBAL_HELP_KO = "GLOBAL HELP KO \"%s\"\n";
g_string RESPONSE_GLOBAL_HELP_START = "GLOBAL HELP START\n";
g_string RESPONSE_GLOBAL_HELP_END = "GLOBAL HELP END\n";
g_string RESPONSE_GLOBAL_INFO_KO = "GLOBAL INFO KO \"%s\"\n";
g_string RESPONSE_GLOBAL_LIST_KO = "GLOBAL LIST KO \"%s\"\n";
g_string RESPONSE_GLOBAL_SUBSCRIBED_KO = "GLOBAL SUBSCRIBED KO \"%s\"\n";
g_string RESPONSE_GLOBAL_USE_KO = "GLOBAL USE KO \"%s\"\n";
g_string RESPONSE_CHANNEL_CREATE_OK = "CHANNEL CREATE OK \"%s\"\n";
g_string RESPONSE_CHANNEL_CREATE_KO = "CHANNEL CREATE KO \"%s\"\n";
g_string RESPONSE_CHANNEL_INFO_OK = "CHANNEL INFO OK \"%s\"\n";
g_string RESPONSE_CHANNEL_INFO_KO = "CHANNEL INFO KO \"%s\"\n";
g_string RESPONSE_CHANNEL_LIST_OK = "CHANNEL LIST OK \"%s\"\n";
g_string RESPONSE_CHANNEL_LIST_KO = "CHANNEL LIST KO \"%s\"\n";
g_string RESPONSE_CHANNEL_LIST_START = "CHANNEL LIST START\n";
g_string RESPONSE_CHANNEL_LIST_END = "CHANNEL LIST END\n";
g_string RESPONSE_CHANNEL_USE_OK = "CHANNEL USE OK \"%s\"\n";
g_string RESPONSE_CHANNEL_USE_KO = "CHANNEL USE KO \"%s\"\n";
g_string RESPONSE_COMMENT_CREATE_OK = "COMMENT CREATE OK \"%s\"\n";
g_string RESPONSE_COMMENT_CREATE_KO = "COMMENT CREATE KO \"%s\"\n";
g_string RESPONSE_COMMENT_LIST_OK = "COMMENT LIST OK \"%s\"\n";
g_string RESPONSE_COMMENT_LIST_KO = "COMMENT LIST KO \"%s\"\n";
g_string RESPONSE_COMMENT_LIST_START = "COMMENT LIST START\n";
g_string RESPONSE_COMMENT_LIST_END = "COMMENT LIST END\n";
g_string RESPONSE_MESSAGE_LIST_OK = "MESSAGE LIST OK \"%s\"\n";
g_string RESPONSE_MESSAGE_LIST_KO = "MESSAGE LIST KO \"%s\"\n";
g_string RESPONSE_MESSAGE_LIST_START = "MESSAGE LIST START\n";
g_string RESPONSE_MESSAGE_LIST_END = "MESSAGE LIST END\n";
g_string RESPONSE_MESSAGE_SEND_OK = "MESSAGE SEND OK \"%s\"\n";
g_string RESPONSE_MESSAGE_SEND_KO = "MESSAGE SEND KO \"%s\"\n";
g_string RESPONSE_SERVER_USE_OK = "SERVER USE OK \"%s\"\n";
g_string RESPONSE_SERVER_USE_KO = "SERVER USE KO \"%s\"\n";
g_string RESPONSE_TEAM_CREATE_OK = "TEAM CREATE OK \"%s\"\n";
g_string RESPONSE_TEAM_CREATE_KO = "TEAM CREATE KO \"%s\"\n";
g_string RESPONSE_TEAM_INFO_OK = "TEAM INFO OK \"%s\"\n";
g_string RESPONSE_TEAM_INFO_KO = "TEAM INFO KO \"%s\"\n";
g_string RESPONSE_TEAM_LIST_OK = "TEAM LIST OK \"%s\"\n";
g_string RESPONSE_TEAM_LIST_KO = "TEAM LIST KO \"%s\"\n";
g_string RESPONSE_TEAM_LIST_START = "TEAM LIST START\n";
g_string RESPONSE_TEAM_LIST_END = "TEAM LIST END\n";
g_string RESPONSE_TEAM_SUBSCRIBERS_OK = "TEAM SUBSCRIBERS OK \"%s\"\n";
g_string RESPONSE_TEAM_SUBSCRIBERS_KO = "TEAM SUBSCRIBERS KO \"%s\"\n";
g_string RESPONSE_TEAM_SUBSCRIBERS_START = "TEAM SUBSCRIBERS START\n";
g_string RESPONSE_TEAM_SUBSCRIBERS_END = "TEAM SUBSCRIBERS END\n";
g_string RESPONSE_TEAM_USE_OK = "TEAM USE OK \"%s\"\n";
g_string RESPONSE_TEAM_USE_KO = "TEAM USE KO \"%s\"\n";
g_string RESPONSE_THREAD_CREATE_OK = "THREAD CREATE OK \"%s\"\n";
g_string RESPONSE_THREAD_CREATE_KO = "THREAD CREATE KO \"%s\"\n";
g_string RESPONSE_THREAD_INFO_OK = "THREAD INFO OK \"%s\"\n";
g_string RESPONSE_THREAD_INFO_KO = "THREAD INFO KO \"%s\"\n";
g_string RESPONSE_THREAD_LIST_OK = "THREAD LIST OK \"%s\"\n";
g_string RESPONSE_THREAD_LIST_KO = "THREAD LIST KO \"%s\"\n";
g_string RESPONSE_THREAD_LIST_START = "THREAD LIST START\n";
g_string RESPONSE_THREAD_LIST_END = "THREAD LIST END\n";
g_string RESPONSE_THREAD_USE_OK = "THREAD USE OK \"%s\"\n";
g_string RESPONSE_THREAD_USE_KO = "THREAD USE KO \"%s\"\n";
g_string RESPONSE_USER_INFO_OK = "USER INFO OK \"%s\"\n";
g_string RESPONSE_USER_INFO_KO = "USER INFO KO \"%s\"\n";
g_string RESPONSE_USER_LIST_OK = "USER LIST OK \"%s\"\n";
g_string RESPONSE_USER_LIST_KO = "USER LIST KO \"%s\"\n";
g_string RESPONSE_USER_LIST_START = "USER LIST START\n";
g_string RESPONSE_USER_LIST_END = "USER LIST END\n";
g_string RESPONSE_USER_LOGIN_OK = "USER LOGIN OK \"%s\"\n";
g_string RESPONSE_USER_LOGIN_KO = "USER LOGIN KO \"%s\"\n";
g_string RESPONSE_USER_LOGOUT_OK = "USER LOGOUT OK \"%s\"\n";
g_string RESPONSE_USER_LOGOUT_KO = "USER LOGOUT KO \"%s\"\n";
g_string RESPONSE_USER_SUBSCRIBE_OK = "USER SUBSCRIBE OK \"%s\"\n";
g_string RESPONSE_USER_SUBSCRIBE_KO = "USER SUBSCRIBE KO \"%s\"\n";
g_string RESPONSE_USER_SUBSCRIPTIONS_OK = "USER SUBSCRIPTIONS OK \"%s\"\n";
g_string RESPONSE_USER_SUBSCRIPTIONS_KO = "USER SUBSCRIPTIONS KO \"%s\"\n";
g_string RESPONSE_USER_SUBSCRIPTIONS_START = "USER SUBSCRIPTIONS START\n";
g_string RESPONSE_USER_SUBSCRIPTIONS_END = "USER SUBSCRIPTIONS END\n";
g_string RESPONSE_USER_UNSUBSCRIBE_OK = "USER UNSUBSCRIBE OK \"%s\"\n";
g_string RESPONSE_USER_UNSUBSCRIBE_KO = "USER UNSUBSCRIBE KO \"%s\"\n";

#endif // SERVER_SRC_DEF_RESPONSE_H
